
#include <stdlib.h>
#include <stdio.h>

#include <debug.h>

#include "usage.h"

void usage(int code)
{
	printf(""
		"usage: zebu [-ptlvh] -i <path/to/input.zb> -o <path/to/output>\n"
		"	-i (or --input)\n"
		"		Specifies path to input file.\n"
		"	-o (or --output)\n"
		"		Specifies path for output files. *without file extension*.\n"
		"		For instance, if one wanted zebu to produce \"dir/foo.c\" and\n"
		"		\"dir/foo.h\", one would invoke zebu with `-o dir/foo`.\n"
		"	-p (or --prefix)\n"
		"		Sets the prefix the generated code should have it's non-`static`\n"
		"		functions and globals. This is useful to avoid symbol-conflicts\n"
		"		when linking multiple parsers generated by zebu. The default\n"
		"		value is \"zebu\".\n"
		"	-t (or --template)\n"
		"		Sets which parser-template zebu should use when generating it's\n"
		"		output. The default value is \"just-tables\".\n"
		"	-l (or --minimize-lexer)\n"
		"		Tells zebu to combine and simplify all tokenizers generated\n"
		"		accross all parser-contexts. This operation may take some time\n"
		"		depending on the language. This option is disabled by default.\n"
		"	-v (or --verbose)\n"
		"		Enables status-update/progress-percentage print-outs for the\n"
		"		time-consuming algorthims: NFA-to-DFA, DFA-simplification,\n"
		"		Lexer-Minimization and LL parser-generation.\n"
		"	-h (or --help):\n"
		"		Prints this help message.\n"
	"");
	
	exit(code);
}


