extern const unsigned zebu_shifts[49][27];
extern const unsigned zebu_reduces[50][24];
extern const unsigned zebu_lexer[98][123];
extern const unsigned zebu_firsts[28][27];
extern const unsigned zebu_starts[50];
extern const unsigned zebu_defaults[48];
extern const unsigned zebu_accepts[99];
extern const char* zebu_grammar_names[29];
struct zebu_state;
struct zebu_state* new_zebu_state();
void zebu_reset(struct zebu_state* this);
void zebu_parse(struct zebu_state* this, const unsigned char* text, size_t length);
void zebu_parse_EOF(struct zebu_state* this);
void free_zebu_state(struct zebu_state* this);
