
# vim: set noai ts=4 sw=4 expandtab:

name: Build & Test

on:
  push:
    branches: [ "main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debug
      run: make buildtype=test verbose=no

  iloc-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install -y valgrind

    - name: Generate Iloc Example
      run: make buildtype=test verbose=no run ARGS="-vl -t fileio-debug -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

    - name: Compile Iloc Example
      run: gcc -Wall -Werror ./-examples/iloc/iloc2.c -o /tmp/test

    - name: Run Iloc Example
      run: valgrind /tmp/test ./-examples/iloc/dynamic.il

  json-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install valgrind

    - name: Generate JSON Example
      run: make buildtype=test verbose=no run ARGS="-vl -t fileio-debug -i ./-examples/json/json.zb -o ./-examples/json/json"

    - name: Compile JSON Example
      run: gcc -Wall -Werror ./-examples/json/json.c -o /tmp/test

    - name: Run JSON Example
      run: valgrind /tmp/test ./-examples/json/input.json

  zebu-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install valgrind

    - name: Generate Zebu Example
      run: make buildtype=test verbose=no run ARGS="-vl -t fileio-debug -i ./-examples/zebu/zebu.zb -o ./-examples/zebu/zebu"

    - name: Compile Zebu Example
      run: gcc -Wall -Werror ./-examples/zebu/zebu.c -o /tmp/test

    - name: Run Zebu Example
      run: valgrind /tmp/test ./-examples/zebu/zebu.zb

  release-build:
    runs-on: ubuntu-latest
    needs: [iloc-example, json-example, zebu-example]
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Release
      run: make

  release-iloc-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install valgrind

    - name: Generate Iloc Example
      run: make run ARGS="-vl -t fileio -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

    - name: Compile Iloc Example
      run: gcc -Wall -Werror ./-examples/iloc/iloc2.c -o /tmp/test

    - name: Run Iloc Example
      run: valgrind /tmp/test ./-examples/iloc/dynamic.il

  release-json-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install valgrind

    - name: Generate JSON Example
      run: make run ARGS="-vl -t fileio -i ./-examples/json/json.zb -o ./-examples/json/json"
      
    - name: Compile JSON Example
      run: gcc -Wall -Werror ./-examples/json/json.c -o /tmp/test

    - name: Run JSON Example
      run: valgrind /tmp/test ./-examples/json/input.json

  release-zebu-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: sudo apt install valgrind

    - name: Generate zebu Example
      run: make run ARGS="-vl -t fileio -i ./-examples/zebu/zebu.zb -o ./-examples/zebu/zebu"
      
    - name: Compile zebu Example
      run: gcc -Wall -Werror ./-examples/zebu/zebu.c -o /tmp/test

    - name: Run zebu Example
      run: valgrind /tmp/test ./-examples/zebu/zebu.zb



















