
# vim: set noai ts=4 sw=4 expandtab:

name: Build & Test

on:
  push:
    branches: [ "main" ]

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debug
      run: make buildtype=debug dotout=no verbose=no

  debug-iloc-example:
    runs-on: ubuntu-latest
    needs: [debug-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Iloc Example
      run: make buildtype=debug dotout=no verbose=no run ARGS="-vl -t fileio -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

  debug-json-example:
    runs-on: ubuntu-latest
    needs: [debug-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run JSON Example
      run: make buildtype=debug dotout=no verbose=no run ARGS="-vl -t fileio -i ./-examples/json/json.zb -o ./-examples/json/json"

  release-build:
    runs-on: ubuntu-latest
    needs: [debug-iloc-example, debug-json-example]
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Release
      run: make

  release-iloc-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Iloc Example
      run: make run ARGS="-vl -t fileio -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

  release-json-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run JSON Example
      run: make run ARGS="-vl -t fileio -i ./-examples/json/json.zb -o ./-examples/json/json"


















