
# vim: set noai ts=4 sw=4 expandtab:

name: Build & Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debug
      run: make buildtype=test dotout=no verbose=no

  iloc-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: apt install -y valgrind

    - name: Generate Iloc Example
      run: make buildtype=test dotout=no verbose=no run ARGS="-vl -t fileio -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

    - name: Compile Iloc Example
      run: gcc -Wall -Werror ./-examples/iloc/iloc2 -o /tmp/test

    - name: Run Iloc Example
      run: valgrind /tmp/test ./-examples/iloc/dynamic.il

  json-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run JSON Example
      run: make buildtype=test dotout=no verbose=no run ARGS="-vl -t fileio -i ./-examples/json/json.zb -o ./-examples/json/json"

  release-build:
    runs-on: ubuntu-latest
    needs: [iloc-example, json-example]
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Release
      run: make

  release-iloc-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependences
      run: apt install valgrind

    - name: Generate Iloc Example
      run: make run ARGS="-vl -t fileio -i ./-examples/iloc/iloc2.zb -o ./-examples/iloc/iloc2"

    - name: Compile Iloc Example
      run: gcc -Wall -Werror ./-examples/iloc/iloc2 -o /tmp/test

    - name: Run Iloc Example
      run: valgrind /tmp/test ./-examples/iloc/dynamic.il

  release-json-example:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Run JSON Example
      run: make run ARGS="-vl -t fileio -i ./-examples/json/json.zb -o ./-examples/json/json"


















