
# vim: set noai ts=4 sw=4 expandtab:

on:
  push:
    branches: [ "main" ]
    tags:
    - 'v*'

jobs:
  upload-release-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Static Release
      run: make LDFLAGS="-static"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    
    - name: Upload Asset Release
      uses: actions/upload-release-asset@v1
      id: release
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gen/release-build/yes-verbose/no-dotout/zebu
          asset_name: zebu
          asset_content_type: application/octet-stream



